# Fish variables
# Generated by 'wal'
set -U wallpaper "/home/kbianco/.wallpapers/wallpaper.jpg"

# Special
set -U background '#1a1e25'
set -U foreground '#cfbdcc'
set -U cursor '#cfbdcc'

# Colors
set -U color0 '#1a1e25'
set -U color1 '#AA676B'
set -U color2 '#CD8871'
set -U color3 '#786E85'
set -U color4 '#8F7891'
set -U color5 '#C37988'
set -U color6 '#7D8291'
set -U color7 '#cfbdcc'
set -U color8 '#90848e'
set -U color9 '#AA676B'
set -U color10 '#CD8871'
set -U color11 '#786E85'
set -U color12 '#8F7891'
set -U color13 '#C37988'
set -U color14 '#7D8291'
set -U color15 '#cfbdcc'

# Shell colors
set -U fish_color_normal normal
set -U fish_color_command AA676B
set -U fish_color_param C37988
set -U fish_pager_color_completion
set -U fish_pager_color_description $fish_color_quote yellow
set -U fish_pager_color_progress brwhite --background=cyan
set -U fish_color_history_current --bold

# FZF colors
set -gx FZF_DEFAULT_OPTS "
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
